name: first_workflow

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step 
              uses: actions/checkout@v2
            - name: Step two
              run: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: "Get-ChildItem Env: | Sort-Object Name"
    macos:
        name: MacOS 
        runs-on: macos-latest
        steps:
            - run: date 
    depends:
        needs: [job1, job2, macos]
        runs-on: macos-latest
        steps: 
            - run: date
